### ISSUE TITLE
roadmapping

### ISSUE THREAD

**Issue by serapath** [playproject-io/wallet#1]
## `@todo`
* [ ] **prepare an EIP/ERC standard proposal**
    * [ ] make wallet feature handling concept
    * [ ] [`wallet#2` - what is the message format used to communicate directly over `.postMessage()`?](https://github.com/playproject-io/wallet/issues/2)
    * [ ] [`wallet#3` - whats the minimum functionality a wallet needs to support to "allow features" & which "atomic" features exist today that wallets should or can support and how do they work?](https://github.com/playproject-io/wallet/issues/3)
    * [ ] [`wallet#4` - how do people implement and specify new features a wallet and dapp could support?](https://github.com/playproject-io/wallet/issues/4)
    * [ ] [`wallet#5` - how to grant/revoke permissions?](https://github.com/playproject-io/wallet/issues/5)
* [ ] implement developer wallet
    * [ ] [`wallet#6` - how to manage permissions?](https://github.com/playproject-io/wallet/issues/6)
    * [ ] [`wallet#7` - profile avatars](https://github.com/playproject-io/wallet/issues/7)

---
Most dapps only support one or a few wallets, but users want to use their favorite wallet (e.g. portis, burner, ...) with all dapps out there
* https://medium.com/@ahoff/the-state-of-ethereum-dapp-desktop-wallet-integrations-1cb6f4815b89

# solution / proposal
**"iframe wallet" could work as follows:**
0. [optional] - the user: opens his e.g. `walletURL=wallet.html` in the browser
1. **`the user`:** opens a dapp in a different browser tab
2. **`the dapp`:** offers a "connect wallet" input field to the user
3. **`the user`:** pastes their `walletURL` and clicks "connect wallet" button
4. **`the dapp`:** creates an iframe with users `src=walletURL` (and maybe `height:0; width:0;`)
5. **`the dapp`:** sends requests to the iframe via `.postMessage(msg)`
6. **`the wallet`:** the tab or browser window with the users wallet (=`wallet.html`) prompts **the user** to confirm interaction with **the dapp**
7. **`the user`:** confirms on their wallet page (=`wallet.html`)
8. **`the wallet`:** sends a response to **the dapp** via .postMessage()
9. **`the dapp`:** receives (=`window.onmessage`) messages from **the wallet** in this controlled way

=> communication between dapp and user's wallet goes back and forth as the user navigates
