### ISSUE TITLE
whats the minimum functionality a wallet needs to support to "allow features" & which "atomic" features exist today that wallets should or can support and how do they work?

### ISSUE THREAD

**Issue by serapath** [playproject-io/wallet#3]
## `@todo`
* [ ] define feature negotiation (as the most basic and only feature
* [ ] define most basic wallet functionality and optional features
    * e.g. `private key management`
    * e.g. https://github.com/portis-project/web-sdk/blob/master/packages/portis-web3/src/index.ts
    * `openWallet`
    * `changeNetwork`
    * `onLogin`
    * `onLogout`
    * `importWallet`
    * `enableGSN` (EIP-1613)
    * `scope` or `permission` (similar to OAuth scope, DApp requests user to share info)
* [ ] define all features of web3js in a module way
    * e.g. `eth_sendTransaction`
* [ ] define all features specified as EIP's
    * e.g. `setting/changing blockchain network` (e.g. EIP-2015)

---
Even the most basic wallet functionality could be a feature and the "out of the box feature" which every wallet needs to support is "feature negotiation" and the most basic possible wallet supports no features at all, but probably every wallet would support a payment feature, but there might be wallets who don't support payments and maybe only deal with storing secrets?
